-- Invite-only beta gate: waitlist + invite codes
-- Migration 082

-- Waitlist table: stores signups with invite tracking
CREATE TABLE IF NOT EXISTS public.waitlist (
  id            uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  email         text        NOT NULL UNIQUE,
  referral_source text      DEFAULT 'direct',
  created_at    timestamptz DEFAULT now(),
  invited_at    timestamptz,
  invite_code   text        REFERENCES public.invite_codes(code) ON DELETE SET NULL
);

-- Invite codes table: one-time codes generated by admins
CREATE TABLE IF NOT EXISTS public.invite_codes (
  id         uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  code       text        NOT NULL UNIQUE,
  created_by uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  used_by    uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  used_at    timestamptz,
  max_uses   integer     DEFAULT 1,
  use_count  integer     DEFAULT 0,
  expires_at timestamptz
);

-- Re-add FK now that invite_codes exists
ALTER TABLE public.waitlist
  DROP CONSTRAINT IF EXISTS waitlist_invite_code_fkey;

ALTER TABLE public.waitlist
  ADD CONSTRAINT waitlist_invite_code_fkey
  FOREIGN KEY (invite_code) REFERENCES public.invite_codes(code) ON DELETE SET NULL;

-- RLS
ALTER TABLE public.waitlist       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invite_codes   ENABLE ROW LEVEL SECURITY;

-- Waitlist: allow anon inserts (public sign-up form uses anon key)
CREATE POLICY "waitlist_anon_insert" ON public.waitlist
  FOR INSERT TO anon
  WITH CHECK (true);

-- Waitlist: service role full access
CREATE POLICY "waitlist_service_all" ON public.waitlist
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- Invite codes: allow anon to SELECT (for validation checks)
CREATE POLICY "invite_codes_anon_select" ON public.invite_codes
  FOR SELECT TO anon
  USING (true);

-- Invite codes: service role full access
CREATE POLICY "invite_codes_service_all" ON public.invite_codes
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- Invite codes: owner can read their own codes
CREATE POLICY "invite_codes_owner_select" ON public.invite_codes
  FOR SELECT TO authenticated
  USING (created_by = auth.uid());

-- Indexes
CREATE INDEX IF NOT EXISTS idx_waitlist_email        ON public.waitlist(email);
CREATE INDEX IF NOT EXISTS idx_waitlist_invite_code  ON public.waitlist(invite_code);
CREATE INDEX IF NOT EXISTS idx_invite_codes_code     ON public.invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_invite_codes_used_by  ON public.invite_codes(used_by);

-- Seed a few launch codes for internal testing
INSERT INTO public.invite_codes (code, max_uses)
VALUES
  ('BITBIT-LAUNCH',  50),
  ('EARLYBIRD-2026', 25),
  ('BETA-ACCESS',    10)
ON CONFLICT (code) DO NOTHING;
