-- Phase 38: Add fiduciary_constraint memory category
-- Extends the category CHECK constraint to support fiduciary constraints
-- generated by sleep consolidation's Game Theory LTV evaluation stage.

-- Drop the existing CHECK constraint and recreate with the new category.
-- Note: Postgres unnamed inline CHECK constraints get auto-generated names.
-- We query pg_constraint to find the exact name.

DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT con.conname INTO constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'memory_palace_entries'
    AND con.contype = 'c'
    AND pg_get_constraintdef(con.oid) LIKE '%category%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE memory_palace_entries DROP CONSTRAINT %I', constraint_name);
  END IF;
END $$;

ALTER TABLE memory_palace_entries ADD CONSTRAINT memory_palace_entries_category_check
  CHECK (category IN (
    'conversation', 'decision', 'pattern', 'fact',
    'relationship', 'pricing', 'convention', 'fiduciary_constraint'
  ));
