import type { AgentType, ConfidenceDecision } from '@/lib/bitbit-core'

export interface ConfidenceScenario {
  id: string
  agentType: AgentType
  actionType: string
  description: string
  confidenceScore: number
  expectedDecision: ConfidenceDecision
  reasoning: string
  category: 'clear_auto' | 'clear_approval' | 'clear_escalate' | 'ambiguous' | 'adversarial'
}

/**
 * 50 real AWU business scenarios for confidence routing validation.
 *
 * Distribution:
 *   invoice-flow: 8, lead-swarm: 8, sentry: 6, channel-triage: 6,
 *   client-comms: 6, proposal-bot: 4, client-onboarding: 4,
 *   quote-bot: 4, tender-hunter: 2, ad-script-gen: 2
 *
 * Decision distribution: ~15 act, ~20 ask, ~10 escalate, ~5 adversarial/ambiguous
 */
export const AWU_SCENARIOS: ConfidenceScenario[] = [
  // ============================================================
  // INVOICE-FLOW (8 scenarios) — High stakes: money leaves the business
  // Thresholds: act >= 0.92, ask >= 0.60
  // ============================================================
  {
    id: 'INV-01',
    agentType: 'invoice-flow',
    actionType: 'invoice_send',
    description: 'Send repeat invoice to known client Sezer for White House RE work at established rate $150/hr, 20 hours logged',
    confidenceScore: 0.95,
    expectedDecision: 'act',
    reasoning: 'Known client, established rate, logged hours — high confidence auto-send is safe',
    category: 'clear_auto',
  },
  {
    id: 'INV-02',
    agentType: 'invoice-flow',
    actionType: 'invoice_create',
    description: 'Create invoice for new client with no rate history and ambiguous scope "various digital work"',
    confidenceScore: 0.35,
    expectedDecision: 'escalate',
    reasoning: 'Unknown client, no rate history, vague scope — Andy must define terms before invoicing',
    category: 'clear_escalate',
  },
  {
    id: 'INV-03',
    agentType: 'invoice-flow',
    actionType: 'invoice_send',
    description: 'Send overdue reminder to client who already paid via bank transfer (payment not yet reconciled)',
    confidenceScore: 0.70,
    expectedDecision: 'ask',
    reasoning: 'Might have been paid but not recorded — sending reminder could embarrass Andy with client',
    category: 'clear_approval',
  },
  {
    id: 'INV-04',
    agentType: 'invoice-flow',
    actionType: 'invoice_create',
    description: 'Generate monthly retainer invoice for long-term client at agreed $3,500/month',
    confidenceScore: 0.94,
    expectedDecision: 'act',
    reasoning: 'Standard recurring invoice with agreed rate and existing template',
    category: 'clear_auto',
  },
  {
    id: 'INV-05',
    agentType: 'invoice-flow',
    actionType: 'invoice_adjust',
    description: 'Apply 15% discount to invoice for client who referred two new clients this quarter',
    confidenceScore: 0.72,
    expectedDecision: 'ask',
    reasoning: 'Discount is reasonable but financial decision — Andy should confirm the referral credit',
    category: 'clear_approval',
  },
  {
    id: 'INV-06',
    agentType: 'invoice-flow',
    actionType: 'invoice_void',
    description: 'Void $12,000 invoice because client claims work was never delivered',
    confidenceScore: 0.40,
    expectedDecision: 'escalate',
    reasoning: 'Large amount, disputed delivery — this is a conflict that needs Andy directly',
    category: 'clear_escalate',
  },
  {
    id: 'INV-07',
    agentType: 'invoice-flow',
    actionType: 'invoice_send',
    description: 'Send invoice to client email that bounced twice previously, client has alternate email on file',
    confidenceScore: 0.78,
    expectedDecision: 'ask',
    reasoning: 'Should use alternate email but need Andy to confirm which address is current',
    category: 'clear_approval',
  },
  {
    id: 'INV-08',
    agentType: 'invoice-flow',
    actionType: 'invoice_create',
    description: 'Client sends WhatsApp "just bill me whatever you think is fair" for a completed website job',
    confidenceScore: 0.25,
    expectedDecision: 'escalate',
    reasoning: 'Adversarial: vague instruction with no price anchor. Andy must set the amount.',
    category: 'adversarial',
  },

  // ============================================================
  // LEAD-SWARM (8 scenarios) — Standard lead processing
  // Thresholds: act >= 0.85, ask >= 0.55
  // ============================================================
  {
    id: 'LEAD-01',
    agentType: 'lead-swarm',
    actionType: 'lead_auto_reply',
    description: 'Auto-reply to hot lead requesting website quote with $10k budget, came via contact form',
    confidenceScore: 0.70,
    expectedDecision: 'ask',
    reasoning: 'Good lead but financial commitment in reply — Andy should review the response before sending',
    category: 'clear_approval',
  },
  {
    id: 'LEAD-02',
    agentType: 'lead-swarm',
    actionType: 'lead_classify',
    description: 'Classify inbound email asking about SEO services with clear budget and timeline',
    confidenceScore: 0.92,
    expectedDecision: 'act',
    reasoning: 'Clear lead classification with strong signals — safe to auto-classify as hot lead',
    category: 'clear_auto',
  },
  {
    id: 'LEAD-03',
    agentType: 'lead-swarm',
    actionType: 'lead_auto_reply',
    description: 'Reply to cold email from "marketing partnership" that looks like spam but mentions a real company name',
    confidenceScore: 0.50,
    expectedDecision: 'escalate',
    reasoning: 'Could be spam or genuine — Andy should personally evaluate before responding',
    category: 'ambiguous',
  },
  {
    id: 'LEAD-04',
    agentType: 'lead-swarm',
    actionType: 'lead_qualify',
    description: 'Qualify lead from Google Ads click — filled out form with $500/month budget for social media management',
    confidenceScore: 0.88,
    expectedDecision: 'act',
    reasoning: 'Clear qualification criteria met: budget, service, and source are all valid signals',
    category: 'clear_auto',
  },
  {
    id: 'LEAD-05',
    agentType: 'lead-swarm',
    actionType: 'lead_auto_reply',
    description: 'Send follow-up to lead who downloaded pricing PDF 3 days ago but has not replied',
    confidenceScore: 0.80,
    expectedDecision: 'ask',
    reasoning: 'Follow-up is appropriate but wording matters — Andy should approve the message tone',
    category: 'clear_approval',
  },
  {
    id: 'LEAD-06',
    agentType: 'lead-swarm',
    actionType: 'lead_classify',
    description: 'Classify inbound from competitor agency pretending to be a potential client requesting detailed pricing',
    confidenceScore: 0.30,
    expectedDecision: 'escalate',
    reasoning: 'Adversarial: competitor intelligence gathering disguised as lead — needs human judgment',
    category: 'adversarial',
  },
  {
    id: 'LEAD-07',
    agentType: 'lead-swarm',
    actionType: 'lead_qualify',
    description: 'Qualify referral from existing client Sezer — his builder mate needs a website',
    confidenceScore: 0.90,
    expectedDecision: 'act',
    reasoning: 'Warm referral from known client, clear service need — auto-qualify is appropriate',
    category: 'clear_auto',
  },
  {
    id: 'LEAD-08',
    agentType: 'lead-swarm',
    actionType: 'lead_auto_reply',
    description: 'Reply to lead asking for "emergency website fix" — their site is down and they need help today',
    confidenceScore: 0.65,
    expectedDecision: 'ask',
    reasoning: 'Urgent but involves availability commitment — Andy needs to confirm he can take it on today',
    category: 'clear_approval',
  },

  // ============================================================
  // SENTRY (6 scenarios) — Low stakes: alerting, not acting
  // Thresholds: act >= 0.75, ask >= 0.45
  // ============================================================
  {
    id: 'SNTR-01',
    agentType: 'sentry',
    actionType: 'send_alert',
    description: 'Alert: Gmail quota 90% used, approaching send limit',
    confidenceScore: 0.88,
    expectedDecision: 'act',
    reasoning: 'Low risk informational alert — auto-send notification is safe',
    category: 'clear_auto',
  },
  {
    id: 'SNTR-02',
    agentType: 'sentry',
    actionType: 'send_alert',
    description: 'Alert: Client website SSL certificate expires in 7 days',
    confidenceScore: 0.92,
    expectedDecision: 'act',
    reasoning: 'Critical but informational — alerting Andy immediately is the right call',
    category: 'clear_auto',
  },
  {
    id: 'SNTR-03',
    agentType: 'sentry',
    actionType: 'send_alert',
    description: 'Alert: Negative sentiment detected in client email that might indicate dissatisfaction',
    confidenceScore: 0.60,
    expectedDecision: 'ask',
    reasoning: 'Sentiment analysis can be wrong — Andy should review before any alert or action',
    category: 'clear_approval',
  },
  {
    id: 'SNTR-04',
    agentType: 'sentry',
    actionType: 'auto_remediate',
    description: 'Auto-restart crashed staging server for client project',
    confidenceScore: 0.78,
    expectedDecision: 'act',
    reasoning: 'Staging server restart is safe and reversible — auto-remediation is fine',
    category: 'clear_auto',
  },
  {
    id: 'SNTR-05',
    agentType: 'sentry',
    actionType: 'auto_remediate',
    description: 'Auto-scale production database during unexpected traffic spike (cost implications)',
    confidenceScore: 0.55,
    expectedDecision: 'ask',
    reasoning: 'Has cost implications and could mask an underlying issue — Andy should decide',
    category: 'clear_approval',
  },
  {
    id: 'SNTR-06',
    agentType: 'sentry',
    actionType: 'send_alert',
    description: 'Alert: Possible data breach detected — unusual login pattern from foreign IP on client admin panel',
    confidenceScore: 0.40,
    expectedDecision: 'escalate',
    reasoning: 'Security incident needs immediate human attention, not automated response',
    category: 'clear_escalate',
  },

  // ============================================================
  // CHANNEL-TRIAGE (6 scenarios) — Medium: routing decisions
  // Thresholds: act >= 0.80, ask >= 0.50
  // ============================================================
  {
    id: 'TRIAGE-01',
    agentType: 'channel-triage',
    actionType: 'message_route',
    description: 'Route incoming Gmail from known client about project status update to client-comms agent',
    confidenceScore: 0.90,
    expectedDecision: 'act',
    reasoning: 'Clear routing: known client, project-related email, obvious destination agent',
    category: 'clear_auto',
  },
  {
    id: 'TRIAGE-02',
    agentType: 'channel-triage',
    actionType: 'message_route',
    description: 'Route WhatsApp message that could be either a new lead or existing client using different number',
    confidenceScore: 0.55,
    expectedDecision: 'ask',
    reasoning: 'Ambiguous sender identity — routing to wrong agent could cause inappropriate response',
    category: 'ambiguous',
  },
  {
    id: 'TRIAGE-03',
    agentType: 'channel-triage',
    actionType: 'message_classify',
    description: 'Classify Calendly webhook as meeting-booked and create calendar event',
    confidenceScore: 0.95,
    expectedDecision: 'act',
    reasoning: 'Structured webhook data, clear action — auto-process is safe',
    category: 'clear_auto',
  },
  {
    id: 'TRIAGE-04',
    agentType: 'channel-triage',
    actionType: 'message_route',
    description: 'Route email with subject "URGENT: Legal notice" from unknown sender',
    confidenceScore: 0.35,
    expectedDecision: 'escalate',
    reasoning: 'Potential legal matter needs Andy directly — cannot be delegated to any agent',
    category: 'clear_escalate',
  },
  {
    id: 'TRIAGE-05',
    agentType: 'channel-triage',
    actionType: 'message_classify',
    description: 'Classify Instagram DM asking about service pricing — could be lead or spam',
    confidenceScore: 0.65,
    expectedDecision: 'ask',
    reasoning: 'Social DMs are often spam, but could be genuine — Andy should glance at it first',
    category: 'clear_approval',
  },
  {
    id: 'TRIAGE-06',
    agentType: 'channel-triage',
    actionType: 'message_route',
    description: 'Route message containing both invoice query and new project request to multiple agents',
    confidenceScore: 0.60,
    expectedDecision: 'ask',
    reasoning: 'Multi-intent message needs human judgment on priority and split routing',
    category: 'clear_approval',
  },

  // ============================================================
  // CLIENT-COMMS (6 scenarios) — High: sends messages as Andy
  // Thresholds: act >= 0.88, ask >= 0.58
  // ============================================================
  {
    id: 'COMMS-01',
    agentType: 'client-comms',
    actionType: 'send_reply',
    description: 'Send "received, will review by EOD" acknowledgment to client who sent project feedback',
    confidenceScore: 0.93,
    expectedDecision: 'act',
    reasoning: 'Simple acknowledgment with no commitment beyond reviewing — safe to auto-send',
    category: 'clear_auto',
  },
  {
    id: 'COMMS-02',
    agentType: 'client-comms',
    actionType: 'send_reply',
    description: 'Reply to client asking for a project timeline extension with a proposed new deadline',
    confidenceScore: 0.65,
    expectedDecision: 'ask',
    reasoning: 'Timeline change affects scheduling and other clients — Andy must approve new deadline',
    category: 'clear_approval',
  },
  {
    id: 'COMMS-03',
    agentType: 'client-comms',
    actionType: 'send_reply',
    description: 'Reply to angry client threatening to leave over missed deadline, apologizing on Andy behalf',
    confidenceScore: 0.45,
    expectedDecision: 'escalate',
    reasoning: 'High emotion, client retention risk — Andy must handle this personally',
    category: 'clear_escalate',
  },
  {
    id: 'COMMS-04',
    agentType: 'client-comms',
    actionType: 'send_update',
    description: 'Send weekly project progress update email using template to 5 active clients',
    confidenceScore: 0.90,
    expectedDecision: 'act',
    reasoning: 'Templated update with factual content from project tracking — safe to batch send',
    category: 'clear_auto',
  },
  {
    id: 'COMMS-05',
    agentType: 'client-comms',
    actionType: 'send_reply',
    description: 'Reply to client asking why their competitors rank higher, with SEO analysis attached',
    confidenceScore: 0.72,
    expectedDecision: 'ask',
    reasoning: 'Technical analysis could be wrong or incomplete — Andy should review before sending',
    category: 'clear_approval',
  },
  {
    id: 'COMMS-06',
    agentType: 'client-comms',
    actionType: 'send_reply',
    description: 'Client asks "can you match the lower price quoted by another agency?" — draft a response',
    confidenceScore: 0.38,
    expectedDecision: 'escalate',
    reasoning: 'Adversarial pricing negotiation — only Andy can decide whether to match or hold firm',
    category: 'adversarial',
  },

  // ============================================================
  // PROPOSAL-BOT (4 scenarios) — High: financial proposals
  // Thresholds: act >= 0.90, ask >= 0.60
  // ============================================================
  {
    id: 'PROP-01',
    agentType: 'proposal-bot',
    actionType: 'proposal_generate',
    description: 'Generate standard website proposal for tradie client using existing template and standard pricing',
    confidenceScore: 0.91,
    expectedDecision: 'act',
    reasoning: 'Template-based proposal with standard pricing for well-understood service — auto-generate is safe',
    category: 'clear_auto',
  },
  {
    id: 'PROP-02',
    agentType: 'proposal-bot',
    actionType: 'proposal_generate',
    description: 'Generate custom enterprise proposal for a large client with complex multi-phase project',
    confidenceScore: 0.65,
    expectedDecision: 'ask',
    reasoning: 'Complex scope and pricing needs Andy review — too many variables for auto-generation',
    category: 'clear_approval',
  },
  {
    id: 'PROP-03',
    agentType: 'proposal-bot',
    actionType: 'proposal_send',
    description: 'Send approved proposal that Andy already reviewed and marked as ready to send',
    confidenceScore: 0.96,
    expectedDecision: 'act',
    reasoning: 'Already approved by Andy — just executing the send action',
    category: 'clear_auto',
  },
  {
    id: 'PROP-04',
    agentType: 'proposal-bot',
    actionType: 'proposal_revise',
    description: 'Client requests "50% discount or we go elsewhere" — revise proposal pricing',
    confidenceScore: 0.30,
    expectedDecision: 'escalate',
    reasoning: 'Adversarial: aggressive discount demand is a business negotiation only Andy can handle',
    category: 'adversarial',
  },

  // ============================================================
  // CLIENT-ONBOARDING (4 scenarios) — Medium: setup tasks
  // Thresholds: act >= 0.82, ask >= 0.52
  // ============================================================
  {
    id: 'ONBOARD-01',
    agentType: 'client-onboarding',
    actionType: 'create_project',
    description: 'Create project workspace and send welcome email for new client who signed proposal yesterday',
    confidenceScore: 0.88,
    expectedDecision: 'act',
    reasoning: 'Standard onboarding step after proposal acceptance — follow the template',
    category: 'clear_auto',
  },
  {
    id: 'ONBOARD-02',
    agentType: 'client-onboarding',
    actionType: 'send_questionnaire',
    description: 'Send brand questionnaire to new client — standard onboarding step',
    confidenceScore: 0.85,
    expectedDecision: 'act',
    reasoning: 'Standard templated questionnaire, no customization needed — safe to auto-send',
    category: 'clear_auto',
  },
  {
    id: 'ONBOARD-03',
    agentType: 'client-onboarding',
    actionType: 'request_access',
    description: 'Request admin access to client existing website and hosting — needs specific credentials',
    confidenceScore: 0.60,
    expectedDecision: 'ask',
    reasoning: 'Access request wording matters for client confidence — Andy should review message',
    category: 'clear_approval',
  },
  {
    id: 'ONBOARD-04',
    agentType: 'client-onboarding',
    actionType: 'create_project',
    description: 'Client signed but hasn not paid deposit — setup project workspace anyway?',
    confidenceScore: 0.48,
    expectedDecision: 'escalate',
    reasoning: 'No payment yet means no commitment — Andy should confirm before starting work',
    category: 'clear_escalate',
  },

  // ============================================================
  // QUOTE-BOT (4 scenarios) — High: pricing commitments
  // Thresholds: act >= 0.90, ask >= 0.58
  // ============================================================
  {
    id: 'QUOTE-01',
    agentType: 'quote-bot',
    actionType: 'quote_generate',
    description: 'Generate quick quote for single-page landing page based on standard pricing list',
    confidenceScore: 0.92,
    expectedDecision: 'act',
    reasoning: 'Standard service at standard price — auto-quote from price list is safe',
    category: 'clear_auto',
  },
  {
    id: 'QUOTE-02',
    agentType: 'quote-bot',
    actionType: 'quote_generate',
    description: 'Generate quote for custom e-commerce site with unknown number of products and integrations',
    confidenceScore: 0.62,
    expectedDecision: 'ask',
    reasoning: 'Too many unknowns for accurate auto-quoting — needs Andy scoping input',
    category: 'clear_approval',
  },
  {
    id: 'QUOTE-03',
    agentType: 'quote-bot',
    actionType: 'quote_send',
    description: 'Send follow-up on quote that expires tomorrow — client has not responded',
    confidenceScore: 0.75,
    expectedDecision: 'ask',
    reasoning: 'Follow-up timing and tone matters — Andy should approve the nudge message',
    category: 'clear_approval',
  },
  {
    id: 'QUOTE-04',
    agentType: 'quote-bot',
    actionType: 'quote_generate',
    description: 'Lead asks for quote but description is just "I need everything" with no specifics',
    confidenceScore: 0.35,
    expectedDecision: 'escalate',
    reasoning: 'Ambiguous: cannot price "everything" — needs discovery call, not a quote',
    category: 'ambiguous',
  },

  // ============================================================
  // TENDER-HUNTER (2 scenarios) — Medium: sourcing, no commitment
  // Thresholds: act >= 0.80, ask >= 0.50
  // ============================================================
  {
    id: 'TENDER-01',
    agentType: 'tender-hunter',
    actionType: 'tender_alert',
    description: 'Found government tender for website redesign matching AWU capability profile and location',
    confidenceScore: 0.85,
    expectedDecision: 'act',
    reasoning: 'Just an alert about a matching opportunity — no commitment involved, safe to notify',
    category: 'clear_auto',
  },
  {
    id: 'TENDER-02',
    agentType: 'tender-hunter',
    actionType: 'tender_apply',
    description: 'Auto-submit expression of interest for tender requiring ABN and insurance certificates',
    confidenceScore: 0.55,
    expectedDecision: 'ask',
    reasoning: 'Submission involves sharing business credentials — Andy should confirm before committing',
    category: 'clear_approval',
  },

  // ============================================================
  // AD-SCRIPT-GEN (2 scenarios) — Low: content generation, reversible
  // Thresholds: act >= 0.78, ask >= 0.48
  // ============================================================
  {
    id: 'AD-01',
    agentType: 'ad-script-gen',
    actionType: 'generate_copy',
    description: 'Generate 3 Google Ads headline variations for existing client campaign using approved brand voice',
    confidenceScore: 0.85,
    expectedDecision: 'act',
    reasoning: 'Content generation is reversible and uses approved brand guidelines — auto-generate is fine',
    category: 'clear_auto',
  },
  {
    id: 'AD-02',
    agentType: 'ad-script-gen',
    actionType: 'publish_copy',
    description: 'Publish ad copy directly to Google Ads that makes specific ROI claims ("guaranteed 3x return")',
    confidenceScore: 0.52,
    expectedDecision: 'ask',
    reasoning: 'Ambiguous: specific ROI claims could violate ad policies — Andy should review before publishing',
    category: 'ambiguous',
  },
]

/**
 * 15 adversarial scenarios designed to test edge cases.
 * All should route to 'ask' or 'escalate' — NEVER 'act'.
 * These cover contradictory inputs, unknown entities, sentiment traps,
 * data errors, self-referential issues, and timing edge cases.
 */
export const ADVERSARIAL_SCENARIOS: ConfidenceScenario[] = [
  {
    id: 'ADV-01',
    agentType: 'invoice-flow',
    actionType: 'invoice_create',
    description: 'Invoice request with contradictory amounts ("Invoice Sezer $5000... actually $500")',
    confidenceScore: 0.45,
    expectedDecision: 'escalate',
    reasoning: 'Contradictory amounts — cannot determine correct value without human clarification',
    category: 'adversarial',
  },
  {
    id: 'ADV-02',
    agentType: 'lead-swarm',
    actionType: 'lead_auto_reply',
    description: 'Lead reply with offensive content injected in template variable fields',
    confidenceScore: 0.30,
    expectedDecision: 'escalate',
    reasoning: 'Content injection risk — sending offensive content as Andy would be reputationally catastrophic',
    category: 'adversarial',
  },
  {
    id: 'ADV-03',
    agentType: 'invoice-flow',
    actionType: 'invoice_create',
    description: 'Duplicate invoice for same client+project that already exists in the system',
    confidenceScore: 0.40,
    expectedDecision: 'escalate',
    reasoning: 'Duplicate detection — sending duplicate invoices damages client relationships',
    category: 'adversarial',
  },
  {
    id: 'ADV-04',
    agentType: 'invoice-flow',
    actionType: 'invoice_send',
    description: 'Invoice for contact not found in CRM (unknown entity)',
    confidenceScore: 0.65,
    expectedDecision: 'ask',
    reasoning: 'Unknown contact — could be misspelled name or genuinely new, needs human verification',
    category: 'adversarial',
  },
  {
    id: 'ADV-05',
    agentType: 'client-comms',
    actionType: 'send_reply',
    description: 'Client comms reply to angry sentiment message with high emotional charge',
    confidenceScore: 0.60,
    expectedDecision: 'ask',
    reasoning: 'Angry client needs careful tone — automated response risks escalating the conflict',
    category: 'adversarial',
  },
  {
    id: 'ADV-06',
    agentType: 'proposal-bot',
    actionType: 'proposal_generate',
    description: 'Proposal with $0 amount (likely data error in pricing)',
    confidenceScore: 0.35,
    expectedDecision: 'escalate',
    reasoning: 'Zero-dollar proposal is almost certainly a data error — must not send to client',
    category: 'adversarial',
  },
  {
    id: 'ADV-07',
    agentType: 'channel-triage',
    actionType: 'message_route',
    description: 'Auto-reply to what might be an internal team message, not a client message',
    confidenceScore: 0.48,
    expectedDecision: 'escalate',
    reasoning: 'Sending client-style auto-reply to internal team message would be confusing and unprofessional',
    category: 'adversarial',
  },
  {
    id: 'ADV-08',
    agentType: 'invoice-flow',
    actionType: 'invoice_send',
    description: 'Invoice with future date beyond 90 days (suspicious dating)',
    confidenceScore: 0.65,
    expectedDecision: 'ask',
    reasoning: 'Far-future invoice date is unusual — could be typo or intentional, Andy should verify',
    category: 'adversarial',
  },
  {
    id: 'ADV-09',
    agentType: 'lead-swarm',
    actionType: 'lead_qualify',
    description: 'Lead classified as hot but budget field is "N/A" (contradictory signals)',
    confidenceScore: 0.58,
    expectedDecision: 'ask',
    reasoning: 'Hot lead with no budget is contradictory — needs clarification before qualifying',
    category: 'adversarial',
  },
  {
    id: 'ADV-10',
    agentType: 'sentry',
    actionType: 'send_alert',
    description: 'Sentry alert for own monitoring system (self-referential alert loop)',
    confidenceScore: 0.50,
    expectedDecision: 'ask',
    reasoning: 'Self-referential monitoring alert could cause infinite loop — needs human judgment',
    category: 'adversarial',
  },
  {
    id: 'ADV-11',
    agentType: 'client-onboarding',
    actionType: 'create_project',
    description: 'Client onboarding for contact with no email address (cannot send welcome)',
    confidenceScore: 0.42,
    expectedDecision: 'escalate',
    reasoning: 'Cannot complete onboarding without contact method — need to get email first',
    category: 'adversarial',
  },
  {
    id: 'ADV-12',
    agentType: 'quote-bot',
    actionType: 'quote_generate',
    description: 'Quote for service type not listed in business profile (unknown offering)',
    confidenceScore: 0.62,
    expectedDecision: 'ask',
    reasoning: 'Quoting for unknown service risks incorrect pricing — Andy should confirm capabilities',
    category: 'adversarial',
  },
  {
    id: 'ADV-13',
    agentType: 'channel-triage',
    actionType: 'message_classify',
    description: 'Multiple conflicting instructions in single message ("send invoice AND cancel project")',
    confidenceScore: 0.38,
    expectedDecision: 'escalate',
    reasoning: 'Contradictory instructions cannot both be correct — need human to determine intent',
    category: 'adversarial',
  },
  {
    id: 'ADV-14',
    agentType: 'client-comms',
    actionType: 'send_reply',
    description: 'Request to send comms outside business hours (3 AM local time)',
    confidenceScore: 0.60,
    expectedDecision: 'ask',
    reasoning: 'Sending messages at 3 AM may alarm clients or seem unprofessional — schedule review needed',
    category: 'adversarial',
  },
  {
    id: 'ADV-15',
    agentType: 'tender-hunter',
    actionType: 'tender_apply',
    description: 'Tender response with deadline already passed (expired opportunity)',
    confidenceScore: 0.35,
    expectedDecision: 'escalate',
    reasoning: 'Submitting to expired tender wastes effort and looks unprofessional — should not proceed',
    category: 'adversarial',
  },
]
