/**
 * R&D Scout Skill Type Definitions
 *
 * Types for market research, product opportunity identification,
 * and SEO trend analysis. Used by the R&D Scout skill to structure
 * research reports and track product opportunities.
 */

/**
 * A product opportunity identified from supplier platforms (Alibaba, 1688)
 *
 * Contains all relevant data for evaluating a potential product,
 * including supplier info, pricing, and margin estimates.
 */
export interface ProductOpportunity {
  /** Product title from supplier listing */
  title: string;

  /** Unit price in USD (converted from CNY if needed) */
  price: number;

  /** Supplier name or store ID */
  supplier: string;

  /** Direct link to supplier listing */
  url: string;

  /** Product image URL for quick visual reference */
  image: string;

  /** Product category (e.g., 'skincare', 'haircare', 'tools') */
  category: string;

  /** Estimated margin percentage based on competitor pricing */
  marginEstimate: number;

  /** Minimum order quantity */
  moq?: number;

  /** Key selling points or features */
  features?: string[];

  /** Potential compliance or IP concerns */
  complianceNotes?: string;
}

/**
 * SEO trend data for a keyword or product category
 *
 * Tracks search volume, competition, and trend direction
 * to identify opportunities aligned with market demand.
 */
export interface SEOTrendData {
  /** Target keyword or phrase */
  keyword: string;

  /** Estimated monthly search volume */
  searchVolume: number;

  /** Month-over-month search volume history (last 12 months) */
  monthlySearches: number[];

  /** Competition level: 'low' | 'medium' | 'high' */
  competition: 'low' | 'medium' | 'high';

  /** Whether a recent spike in searches was detected */
  spikeDetected: boolean;

  /** Percentage change from previous period */
  trendDirection: number;

  /** Related keywords worth targeting */
  relatedKeywords?: string[];
}

/**
 * Complete research report generated by R&D Scout
 *
 * Aggregates product opportunities and SEO trends into
 * an actionable report for product decisions.
 */
export interface ResearchReport {
  /** ISO timestamp when report was generated */
  generatedAt: string;

  /** Report ID for tracking and reference */
  reportId: string;

  /** Product opportunities identified in this research cycle */
  opportunities: ProductOpportunity[];

  /** SEO trend data for tracked keywords */
  trends: SEOTrendData[];

  /** Executive summary of findings and recommendations */
  summary: string;

  /** Specific action items or next steps */
  recommendations: string[];

  /** Categories that were scanned in this research cycle */
  categoriesScanned: string[];

  /** Any errors or limitations encountered during research */
  errors?: string[];
}

/**
 * Configuration for R&D Scout research pipeline
 *
 * Defines what categories to scan, how many products to evaluate,
 * and which keywords to track for SEO trends.
 */
export interface RDScoutConfig {
  /** Product categories to scan on supplier platforms */
  targetCategories: string[];

  /** Maximum products to evaluate per category */
  maxProductsPerCategory: number;

  /** Keywords to track for SEO trend analysis */
  seoKeywords: string[];

  /** Minimum margin threshold for opportunity inclusion (percentage) */
  minMarginThreshold?: number;

  /** Maximum product price in USD */
  maxPrice?: number;

  /** Whether to include MOQ filtering */
  maxMoq?: number;

  /** Enabled data sources for scraping */
  enabledSources?: {
    alibaba?: boolean;
    aliexpress?: boolean;
    amazon?: boolean;
  };
}
