export * from './types'
export { gmailAdapter } from './gmail'
export { outlookAdapter } from './outlook'
export { imessageAdapter } from './imessage'
export { calendarAdapter } from './calendar'
export { googleCalendarAdapter, pullGoogleCalendarEvents } from './google-calendar'
export { remindersAdapter } from './reminders'
export { clickupAdapter } from './clickup'
export { ga4Adapter } from './ga4'
export { wordpressAdapter } from './wordpress'
export { cluelyAdapter } from './cluely'
export { xeroAdapter } from './xero'
export { synthesize, getAllAdapters, getAdapter } from './synthesizer'
export type { SynthesisOptions } from './synthesizer'
