/**
 * Generators for the per-project scaffolding files.
 *
 * On intake we write two files into the new project folder:
 *   - CLAUDE.md    — context-hierarchy doc workers read at the start
 *                    of every cycle (loaded automatically by claude-cli).
 *   - PLAYBOOK.md  — initial conventions / pitfalls / operating notes
 *                    that the overseer later rewrites from lessons.
 *
 * Both files are deterministic Markdown built from the ParsedScope.
 * No LLM call here — keep intake cheap and side-effect free.
 */

import { SERVICE_LABELS } from './services.js';
import { SPECIALIST_DESCRIPTIONS } from './specialists.js';
import type { ParsedScope } from './types.js';

function fmtList(items: string[]): string {
  if (items.length === 0) return '_(none specified)_';
  return items.map((s) => `- ${s}`).join('\n');
}

/**
 * Build the CLAUDE.md a worker dropped into this project will see.
 *
 * Patterned after the operator's own CLAUDE.md hierarchy:
 *   1. What this project IS
 *   2. Tech stack
 *   3. Milestones (the arc of the engagement)
 *   4. Open task backlog (what to pick up next)
 *   5. Acceptance criteria (how "done" is judged)
 *   6. Who's involved (specialist roles)
 *   7. Conventions / always-do, never-do (kept short; PLAYBOOK has more)
 */
export function buildClaudeMd(scope: ParsedScope): string {
  const serviceLabel = SERVICE_LABELS[scope.serviceType];

  const milestoneBlock = scope.milestones.length
    ? scope.milestones
        .map(
          (m, i) =>
            `### ${i + 1}. ${m.title}${m.target ? ` _(${m.target})_` : ''}\n${m.description}`,
        )
        .join('\n\n')
    : '_(none specified)_';

  const taskBlock = scope.tasks.length
    ? scope.tasks
        .map((t) => {
          const tags: string[] = [];
          if (t.milestone) tags.push(t.milestone);
          if (t.owner) tags.push(t.owner);
          const suffix = tags.length ? `  _(${tags.join(' · ')})_` : '';
          return `- [ ] ${t.title}${suffix}`;
        })
        .join('\n')
    : '_(no tasks defined yet)_';

  const specialistsBlock = scope.specialists.length
    ? scope.specialists
        .map((s) => `- **${s}** — ${SPECIALIST_DESCRIPTIONS[s]}`)
        .join('\n')
    : '_(none assigned)_';

  return `# ${scope.projectName}

${scope.summary}

> **Service:** ${serviceLabel} &middot; **Complexity:** ${scope.complexity}${scope.client ? ` &middot; **Client:** ${scope.client}` : ''}${scope.estimatedDuration ? ` &middot; **Estimate:** ${scope.estimatedDuration}` : ''}

## Tech Stack

${fmtList(scope.techStack)}

## Milestones

${milestoneBlock}

## Task Backlog

${taskBlock}

## Acceptance Criteria

${fmtList(scope.acceptanceCriteria)}

## Specialist Agents

${specialistsBlock}

## Always Do

- Read this CLAUDE.md and PLAYBOOK.md before making non-trivial changes.
- Match the existing patterns in the codebase — naming, structure, error handling.
- Verify changes (tests, type checks, smoke runs) before reporting done.
- For risky operations (deletes, force pushes, schema migrations, secret changes), describe the plan and stop — escalate to the operator.

## Never Do

- Do not rewrite scope on your own — propose changes back to the operator.
- Do not introduce new dependencies without flagging them in your final summary.
- Do not skip tests / type checks to make a worker cycle finish faster.

---

_This file was generated by the BitBit Scope Intake pipeline. It will be edited as the project evolves; the PLAYBOOK.md alongside captures accumulated lessons._
`;
}

/**
 * Build the initial PLAYBOOK.md. Kept light — it grows as lessons
 * accumulate; the overseer's rewriter (src/memory/playbook.ts) takes
 * over once 3+ lessons have been captured.
 */
export function buildPlaybookMd(scope: ParsedScope): string {
  const serviceLabel = SERVICE_LABELS[scope.serviceType];

  const conventions: string[] = [];
  conventions.push(`Stay scoped to ${serviceLabel} concerns; flag anything outside that umbrella.`);
  if (scope.techStack.length > 0) {
    conventions.push(`Default tech stack: ${scope.techStack.join(', ')}. Don't introduce alternatives without operator approval.`);
  }
  if (scope.specialists.length > 0) {
    conventions.push(`Engage the right specialist agent for the task — see CLAUDE.md for the roster.`);
  }

  const pitfalls: string[] = [
    'No lessons captured yet — this section grows as worker cycles complete.',
  ];

  const operatingNotes: string[] = [
    `Complexity estimate: **${scope.complexity}**. Adjust per-task budgets accordingly.`,
  ];
  if (scope.estimatedDuration) {
    operatingNotes.push(`Estimated duration: ${scope.estimatedDuration}.`);
  }
  if (scope.client) {
    operatingNotes.push(`Stakeholder: ${scope.client}.`);
  }
  if (scope.notes) {
    operatingNotes.push(`Parser notes: ${scope.notes}`);
  }

  return `# ${scope.projectName} — Playbook

_Initial playbook seeded from the scope intake. The overseer will rewrite this file as lessons accumulate (see \`src/memory/playbook.ts\`)._

## About this project

${scope.summary}

## Conventions

${conventions.map((c) => `- ${c}`).join('\n')}

## Pitfalls

${pitfalls.map((p) => `- ${p}`).join('\n')}

## Operating notes

${operatingNotes.map((n) => `- ${n}`).join('\n')}
`;
}
