import type { ProviderPlugin } from './types'
import { blueBubblesProvider } from './providers/bluebubbles'

/**
 * Built-in provider definitions. These ship with BitBit and have
 * adapter code in src/lib/channels/. Custom providers are registered
 * at runtime from org_connections rows.
 */
export const builtInProviders: ProviderPlugin[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Read, draft, and send emails',
    category: 'communication',
    auth: { method: 'oauth' },
    defaultTransport: 'poll',
    capabilities: ['pull', 'send'],
  },
  {
    id: 'outlook',
    name: 'Outlook',
    description: 'Read and send Outlook emails',
    category: 'communication',
    auth: { method: 'bridge' },
    defaultTransport: 'bridge',
    capabilities: ['push', 'send'],
  },
  blueBubblesProvider,
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    description: 'Message clients on WhatsApp',
    category: 'communication',
    auth: { method: 'guided' },
    defaultTransport: 'poll',
    capabilities: ['pull', 'send'],
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Manage your calendar',
    category: 'productivity',
    auth: { method: 'oauth' },
    defaultTransport: 'poll',
    capabilities: ['pull'],
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Sync tasks and projects',
    category: 'productivity',
    auth: { method: 'oauth' },
    defaultTransport: 'poll',
    capabilities: ['pull'],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Manage scheduling and bookings',
    category: 'productivity',
    auth: { method: 'oauth' },
    defaultTransport: 'webhook',
    capabilities: ['webhook'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Track payments and invoices',
    category: 'finance',
    auth: { method: 'api_key' },
    defaultTransport: 'webhook',
    capabilities: ['webhook'],
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Send automated emails',
    category: 'communication',
    auth: { method: 'api_key' },
    defaultTransport: 'poll',
    capabilities: ['send'],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Message your team on Slack',
    category: 'communication',
    auth: { method: 'oauth' },
    defaultTransport: 'poll',
    capabilities: ['pull', 'send'],
    comingSoon: true,
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Connect your docs and notes',
    category: 'productivity',
    auth: { method: 'oauth' },
    defaultTransport: 'poll',
    capabilities: ['pull'],
    comingSoon: true,
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Manage contacts and deals',
    category: 'productivity',
    auth: { method: 'oauth' },
    defaultTransport: 'poll',
    capabilities: ['pull'],
    comingSoon: true,
  },
  {
    id: 'xero',
    name: 'Xero',
    description: 'Accounting and invoices',
    category: 'finance',
    auth: { method: 'oauth' },
    defaultTransport: 'poll',
    capabilities: ['pull'],
    comingSoon: true,
  },
]
